CC=g++
CXXFLAGS=-Wall -std=c++11
TARGET=Boardcards
SRCS=./src
INC = -I ./include
OBJS=$(SRCS:.c=.o)
${info SRCS: $(SRCS)}
${info OBJS: $(OBJS)}


# $(TARGET): 
# 	$(CC) -o $(TARGET) 
	
# %.o : %.S
# 	$(CC) -c -o $@ $< $(INC)
# %.o : %.c
# 	$(CC) -c -o $@ $< $(INC)


# .PHONY: clean
# clean:
# 	rm *.o *.elf *.bin

##################################################################
# 指令编译器和选项
# CC=gcc
# CFLAGS=-Wall -std=gnu99
 
# # 目标文件
# TARGET=test
# SRCS = test.c \
#   ./test-add/test-add.c \
#   ./test-sub/test-sub.c
 
# INC = -I./test-add -I./test-sub
 
# OBJS = $(SRCS:.c=.o)
 
# $(TARGET):$(OBJS)
# #	@echo TARGET:$@
# #	@echo OBJECTS:$^
# [tab]$(CC) -o $@ $^
 
# clean:
# [tab]rm -rf $(TARGET) $(OBJS)
 
# %.o:%.c
# [tab]$(CC) $(CFLAGS) $(INC) -o $@ -c $<
